Opetushallitus/kayttooikeus

- build.gradle
> KJHH-856: change deployment artifact search paths

- kayttooikeus-api/pom.xml
- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/YhteystietojenTyypit.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/Anomus.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/Kutsu.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/KutsuOrganisaatio.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/MyonnettyKayttoOikeusRyhmaTapahtuma.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/TextGroup.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/properties/CommonProperties.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/properties/EmailInvitationProperties.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/EmailService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/OppijanumerorekisteriClient.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/impl/OppijanumerorekisteriClientImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/EmailServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/AnomusKasiteltySahkopostiBuilder.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/LocalisationUtils.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/UserDetailsUtil.java
- kayttooikeus-service/src/main/resources/kayttooikeus-service-oph.properties
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/controller/KutsuPopulator.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/EmailServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/external/OppijanumerorekisteriClientTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KutsuServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/util/CreateUtil.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/utiltest/UserDetailsUtilTest.java
- kayttooikeus-service/src/test/resources/henkilo/henkiloDto.json
- src/main/resources/oph-configuration/kayttooikeus.yml.template
- When anomus has been completely handled and something has been granted send anoja email notification
- Remove handled HaettuKayttooikeus properly
> Kjhh 955: email notifications

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/OrganisaatioHenkiloController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/OrganisaatioHenkiloService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/OrganisaatioHenkiloServiceImpl.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/populate/MyonnettyKayttooikeusRyhmaTapahtumaPopulator.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/OrganisaatioHenkiloServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/util/CreateUtil.java
- Disable privileges related to organisaatiohenkilo on passivointi. 
- Enable organisaatiohenkilo when granting new privileges.
> KJHH-992: organisaatiohenkilo passivointi fix

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/ExternalClientsConfig.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/OrikaBeanMapper.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/impl/OrganisaatioClientImpl.java
- kayttooikeus-service/src/main/resources/kayttooikeus-service-oph.properties
- Fetch organisaatio children when using direct fetch from organisaatio-service
> Kjhh 1046: organisaatiocache

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/AnomusController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/OrganisaatioHenkiloServiceImpl.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/OrganisaatioHenkiloServiceTest.java
- Rajapinta käyttöoikeuksien poistoon
> Kjhh 955 kayttooikeuden poisto

- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/KutsuReadDto.java
- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/LocalizableDto.java
- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/LocalizableOrganisaatio.java
- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/TextGroupMapDto.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/enumeration/KutsuOrganisaatioOrder.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/OrikaBeanMapper.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/KutsuController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/KutsuDataRepository.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/KutsuRepository.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/KutsuRepositoryImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/KutsuService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/LocalizationService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/LocalizationServiceImpl.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/controller/KutsuControllerTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/controller/KutsuPopulator.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/KutsuRepositoryTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KutsuServiceTest.java
- kayttooikeus-service/src/test/resources/kutsu/simpleKutsuListaus.json
- Add more stuff to KutsuReadDto
- Use KutsuReadDto on GET /kutsu listing
- Remove kutsu organisation sorting
- Refactoring
- Initial LocalizationService functionality for organisation names.
> KJHH-1012: Allow resend for UI

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/mapper/KayttajaHenkiloEntityMapper.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/HenkiloController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/KayttajaRepository.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/HenkiloService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/HenkiloServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/LdapSynchronizationServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/ldap/LdapService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/ldap/LdapUtils.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/LdapSynchronizationServiceTest.java
Käyttäjätunnuksen vaihdossa nollataan vanhan käyttäjätunnuksen salasana (ennen poistettiin koko käyttäjätunnus)
> KJHH-1104: Käyttäjätunnuksen vaihto hajottaa istunnon

- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/HenkilohakuCriteriaDto.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/HenkiloHibernateRepository.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/criteria/HenkiloCriteria.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/HenkiloRepositoryImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/HenkiloServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/HenkilohakuBuilder.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/HenkiloRepositoryTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/impl/HenkiloServiceImplTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/HenkiloServiceTest.java
Korjaa samalla passivoitujen organisaatiohenkilöiden haun (KJHH-1115)
> KJHH-1113: Korjaa "ei aliorganisaatioita" haun oph-virkailijoille

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/criteria/HenkiloCriteria.java
Henkilöhaku palauttaa vähemmän tuloksia useammalla hakutermilla.
> KJHH-1139: Return less results with more than one searchterm in henkilöhaku

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttoOikeusServiceImpl.java
Ongelma tapahtui kun rekisterinpitäjällä oli muitakin käyttäjärooleja.
> KJHH-1190: Fix rekisterinpitäjä getting empty array of Kayttooikeusryhmat

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/KayttoOikeusRyhmaMyontoViiteRepository.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/criteria/AnomusCriteria.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/criteria/MyontooikeusCriteria.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/KayttoOikeusRyhmaMyontoViiteRepositoryImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/anomus/MyontooikeusMapper.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusServiceTest.java
Myöntöviitesuodatus ei toiminut oikein jos käyttäjällä oli useampi organisaatio
> KJHH-1212: Korjaa anomuslistauksen myöntöviitesuodatuksen

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/FunctionalUtils.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusServiceTest.java
Disablointi ei toiminut oikein jos käyttäjällä oli useampi organisaatio
> KJHH-1218: Korjaa anomuksien käsittelyn disabloinnin

- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/HenkilohakuCriteriaDto.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/HenkiloController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/HenkiloHibernateRepository.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/criteria/HenkiloCriteria.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/HenkiloRepositoryImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/HenkiloService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/HenkiloServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/HenkilohakuBuilder.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/HenkiloServiceTest.java
henkilöhakuun rajapinta, joka palauttaa koko tulosjoukon koon
> Kjhh 1280 -  Näytetään hakutulosten kokonaissumma hakutulosten yhteydessä

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusServiceTest.java
Myöntöoikeudet eivät toimineet oikein jos anojalla oli samaan organisaatioon useampi anomus.
> KJHH-1315: Korjaa myöntöoikeudet

- kayttooikeus-service/pom.xml
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/properties/KayttooikeusProperties.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/scheduling/LahetaUusienAnomuksienIlmoituksetTask.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/scheduling/LdapSynkronointiTask.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/scheduling/PoistaVanhentuneetKayttooikeudetTask.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/scheduling/ScheduledTasks.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/scheduling/SchedulingClusterConfiguration.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/scheduling/SchedulingConfiguration.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/scheduling/SendExpirationRemindersTask.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/scheduling/UpdateHenkiloNimiCacheTask.java
- kayttooikeus-service/src/main/resources/application.yml
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/HenkiloCacheServiceTest.java
- kayttooikeus-service/src/test/resources/application.yml
- pom.xml
- Lisää useaa instanssia tukeva scheduleri
- Siirrä scheduling propertyt omaan tiedostoon
> KJHH-1301: concurrent scheduler

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/ErrorHandlerAdvice.java
Ei korjaa itse ongelmaa eli uusi pilviinfrastruktuuri syö 5xx virheistä bodyt.
> KJHH-1262: Korjaa UsernameAlreadyExistsExceptionin puuttuva body

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/AnomusController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/HenkiloController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/KayttoOikeusController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/KayttoOikeusRyhmaController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/KutsuController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/OrganisaatioHenkiloController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/PalveluController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/criteria/MyontooikeusCriteria.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/KayttoOikeusRyhmaMyontoViiteRepositoryImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/PermissionCheckerService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/OrganisaatioHenkiloServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/PermissionCheckerServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/KutsuHakuBuilder.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/controller/OrganisaatioHenkiloControllerTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/PermissionCheckerTest.java
> Lisää käyttöoikeus-luku/muokkaus -roolit

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/KutsuService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KutsuServiceTest.java
Passivoitu & hetullinen henkilö aktivoidaan kutsumisen yhteydessä
> Kjhh 1311 - Passivoitu & hetullinen henkilö aktivoidaan kutsumisen yhteydessä

- kayttooikeus-service/src/main/resources/db/migration/V20180521172459831__oiva_kayttooikeudet.sql
- Uusi oikeus oivaan
- Vanhoista oikeuksista uudet oiva-palvelun versiot
> KJHH-1392: Oivan uusi oikeus

- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/Henkilo.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/HenkiloVarmentaja.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/HenkiloServiceImpl.java
- kayttooikeus-service/src/main/resources/db/migration/V20180528123142078__henkilo_varmentaja_suhde.sql
- Henkilön varmentamisen pakollinen toiminnallisuus
> KJHH-1399_henkilon_varmentaminen_osa1

- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/HenkiloLinkitysDto.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/Henkilo.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/HenkiloController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/HenkiloDataRepositoryCustom.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/MyonnettyKayttoOikeusRyhmaTapahtumaRepository.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/HenkiloDataRepositoryImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/HenkiloService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/HenkiloServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/MyonnettyKayttoOikeusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/OrganisaatioHenkiloServiceImpl.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/HenkiloDataRepositoryTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/impl/MyonnettyKayttoOikeusServiceImplTest.java
- Rajapinta palauttamaan henkilön varmentajasuhteet
- Passivoidaan varmentajasuhde jos henkilöillä ei ole enää yhteisiä aktiivisia organisaatioita tai varmentavan henkilön oikeudet sulkeutuvat kaikissa yhteisissä organisaatioissa
> KJHH-1399_varmentajasuhteet_osa2/2

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/criteria/KayttooikeusCriteria.java
> Korjaa käyttäjätunnuksella käyttöoikeuksien haun

- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/KayttooikeusPerustiedotDto.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/MyonnettyKayttoOikeusRyhmaTapahtumaRepositoryImpl.java
- Lisää username and kayttajatyyppi tiedot /henkilo/current/omattiedot API:iin CAS:ia varten
> KJHH-1426_cas_myroles

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/criteria/HenkiloCriteria.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/HenkiloRepositoryImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/HenkilohakuBuilder.java
> Korjaa palvelukäyttäjien haun käyttäjänimellä

- kayttooikeus-service/src/main/resources/db/migration/V20180810085532546__vastuukayttajat_oikeudet.sql
- kayttooikeus-service/src/main/resources/db/migration/V20180815140728319__vastuukayttajat_migrate.sql
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/HaettuKayttooikeusRyhmaRepositoryCustomTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/KutsuRepositoryTest.java
> Lisää vastuukäyttäjät-käyttöoikeuden

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/HaettuKayttooikeusRyhmaRepositoryCustom.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/criteria/AnomusCriteria.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/HaettuKayttooikeusRyhmaRepositoryImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/OrganisaatioHenkiloServiceImpl.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/HaettuKayttooikeusRyhmaRepositoryCustomTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusServiceTest.java
> Korjaa anomuslistauksen tuplaantumisen

- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/KutsuCreateDto.java
- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/KutsuReadDto.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/KutsuOrganisaatio.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
- kayttooikeus-service/src/main/resources/db/migration/V20180830120237532__kutsuoikeusvoimassaolo.sql
> Lisää kutsuun myönnettävien oikeuksien voimassaoloajan

- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/Henkilo.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/Identification.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/Kayttajatiedot.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/ErrorHandlerAdvice.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/IdentificationRepository.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/OrganisaatioHenkiloRepository.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/exception/ValidationException.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/OppijanumerorekisteriClient.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/impl/OppijanumerorekisteriClientImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/IdentificationServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/ldap/LdapService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/ldap/LdapSynchronizer.java
- kayttooikeus-service/src/main/resources/kayttooikeus-service-oph.properties
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/populate/IdentificationPopulator.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/impl/IdentificationServiceImplTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/impl/ldap/LdapSynchronizerTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/IdentificationServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KutsuServiceTest.java
> Tunnisteiden validointi

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/SessionMappingStorageConfiguration.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/scheduling/CasClientSessionCleanerTask.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/scheduling/SchedulingClusterConfiguration.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/security/JdbcSessionMappingStorage.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/security/OphSessionMappingStorage.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/security/SecurityConfigDefault.java
- kayttooikeus-service/src/main/resources/db/migration/V20180910093637402__casclientsession.sql
> Korjaa uloskirjautumisen jos on useampi instanssi ajossa

- kayttooikeus-service/src/main/resources/db/migration/V20181009155321000__koski_tiedonsiirto_luovutuspalvelu_kayttoikeus.sql
Tarvitaan Kosken viranomaisintegraatioita varten
> Lisää Koski tiedonsiirto luovutuspalvelu käyttöoikeus

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/OrganisaatioHenkiloController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/OrganisaatioHenkiloServiceImpl.java
> Lisää crud/read-oikeudet organisaatioOid-rajapintaan

- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/MeDto.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/CasController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/HenkiloService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/OppijanumerorekisteriClient.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/impl/OppijanumerorekisteriClientImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/HenkiloServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
- kayttooikeus-service/src/main/resources/kayttooikeus-service-oph.properties
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/impl/HenkiloServiceImplTest.java
- pom.xml
- Lisää /cas/me deprekoitu rajapinta
- Lisää /cas/myroles deprekoitu rajapinta
> KJHH-1433_cas_me_myroles

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/OrganisaatioClient.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/impl/OrganisaatioClientImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttoOikeusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/PermissionCheckerServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/OrganisaatioMyontoPredicate.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/PermissionCheckerTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KayttoOikeusServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KutsuServiceTest.java
...organisaatioihin.
KJHH-1494
> Lisää käyttöoikeuksien myöntämisen suunniteltuihin

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttajatiedotServiceImpl.java
Käyttäjätunnus on pakollinen kenttä kannassa joten salasanan voi
asettaa vain jos käyttäjällä on käyttäjätunnus asetettuna.
KJHH-1491
> Korjaa salasanan asettamisen validoinnin

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/criteria/AnomusCriteria.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/OrganisaatioService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/PermissionCheckerService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/OrganisaatioClient.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/impl/OrganisaatioClientImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/OrganisaatioHenkiloServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/OrganisaatioServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/PermissionCheckerServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/anomus/MyontooikeusMapper.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/KutsuHakuBuilder.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/PermissionCheckerTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/external/OrganisaatioClientTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KutsuServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/OrganisaatioHenkiloTest.java
> Korjaa käyttöoikeuksien myöntämisen suunniteltuun organisaatioon

- kayttooikeus-service/src/main/resources/db/migration/V20181130140008845__muutostieto_palvelu.sql
- Erilliset oikeudet muutostietopalveluun
> KJHH-1517 muutostieto oikeudet

- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/LakkautettuOrganisaatio.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/LakkautettuOrganisaatioRepository.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/LakkautettuOrganisaatioRepositoryCustom.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/criteria/AnomusCriteria.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/LakkautettuOrganisaatioRepositoryImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/OrganisaatioHenkiloService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttoOikeusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/OrganisaatioHenkiloServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/PermissionCheckerServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/anomus/MyontooikeusMapper.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/KutsuHakuBuilder.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/OrganisaatioMyontoPredicate.java
- kayttooikeus-service/src/main/resources/db/migration/V20181127121458012__lakkautettuorganisaatio.sql
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/populate/AnomusPopulator.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/OrganisaatioHenkiloServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/PermissionCheckerTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KutsuServiceTest.java
...organisaatioihin (vain rekisterinpitäjälle).
KJHH-1508
> Lisää käyttöoikeuksien myöntämisen lakkautettuihin

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/PermissionCheckerServiceImpl.java
Suressa on nyt hakemuksen perusteella autorisointi. Ks. https://github.com/Opetushallitus/hakurekisteri/pull/132
> SEC-68 jos sure ei anna lupaa, ei kysytä lisäksi atarulta ja haku-appilta

- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/KayttooikeusPerustiedotDto.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/Henkilo.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/KayttoOikeusRyhma.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/OrganisaatioHenkilo.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/Palvelu.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/mapper/KayttooikeusPerustietoDtoConverter.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/KayttoOikeusController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/MyonnettyKayttoOikeusRyhmaTapahtumaRepositoryCustom.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/MyonnettyKayttoOikeusRyhmaTapahtumaRepositoryImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttoOikeusServiceImpl.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/MyonnettyKayttoOikeusRyhmaTapahtumaRepositoryTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/populate/OrganisaatioHenkiloKayttoOikeusPopulator.java
- Muuttaa rajapinnan tulosjoukon koon rajoittamisen käyttöoikeuksien määrästä henkilöiden määrään
> KJHH-1542: Hämäävä limit

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/CookieConfiguration.java
- src/main/resources/oph-configuration/kayttooikeus.yml.template
- Sallii keksin samesite attribuutin käyttämättä jättämisen
> KJHH-1546 samesite cookie attribute

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/CasController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/IdentificationService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/IdentificationServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/VahvaTunnistusServiceImpl.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/DatabaseService.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/populate/TunnistusTokenPopulator.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/rest/CasRestTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/IdentificationServiceTest.java
"Transaction was marked for rollback only; cannot commit"
KJHH-1537
> Korjaa vahvan tunnistuksen virhekäsittelyn

- .travis.yml
- kayttooikeus-api/pom.xml
- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/permissioncheck/ExternalPermissionService.java
- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/permissioncheck/PermissionCheckRequestDto.java
- kayttooikeus-domain/pom.xml
- kayttooikeus-service/pom.xml
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/properties/UrlConfiguration.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/impl/ExternalPermissionClientImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/PermissionCheckerServiceImpl.java
- kayttooikeus-service/src/main/resources/kayttooikeus-service-oph.properties
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/config/ApplicationTest.java
- kayttooikeus-service/src/test/resources/application.yml
- pom.xml
- src/main/resources/oph-configuration/kayttooikeus.yml.template
- Osoite /varda/api/onr/ estetty ulkoisista osoitteista
- Sallii VARDA external permission check headerin
- Korjaa ulkoisten palveluiden tarkistuksen virheviestin lokituksen
- Nostaa projektin versionumeroa
> KJHH-1551: Support varda external permission check

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/CasController.java
- Poistaa ylimääräiset metodit /logInRedrect rajapinnasta
> KJHH-1559: Remove redundant methods from /logInRedirect apis.

- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/OmatTiedotDto.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/Henkilo.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/KayttoOikeus.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/HenkiloController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/HenkiloDataRepository.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/KayttoOikeusRyhmaRepository.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/HenkiloService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/HenkiloServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
- kayttooikeus-service/src/main/resources/db/migration/V20190207133945934__anomusilmoitus.sql
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/HenkiloDataRepositoryTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/impl/HenkiloServiceImplTest.java
- Rekisterinpitäjälle tilaus anomusilmoituksiin käyttöoikeusryhmäkohtaisesti
> KJHH-823: anomus ilmoitus

- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/permissioncheck/PermissionCheckDto.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/PermissionCheckerService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/OrganisaatioClient.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/impl/OrganisaatioClientImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/PermissionCheckerServiceImpl.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/PermissionCheckerTest.java
- Antaa external-permission-service kutsuun vain sellaiset organisaatiot joihin käyttäjältä löytyy vaadittu oikeus.
> KJHH-1558: external roles

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/AnomusController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/CasController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/DevController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/HenkiloController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/KayttoOikeusController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/KayttoOikeusRyhmaController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/KutsuController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/MyonnettyKayttoOikeusController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/OrganisaatioHenkiloController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/PalveluController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/PalvelukayttajaController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/ServiceToServiceController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/UserDetailsController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/VirkailijaController.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/controller/HenkiloControllerTest.java
> Lisää rajapintoihin accept/content-type tarkistukset

- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/KutsuCreateDto.java
- kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/KutsuReadDto.java
- kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/Henkilo.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/OrikaBeanMapper.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/mapper/KutsuCreateKayttoOikeusRyhmaConverter.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/mapper/KutsuMappers.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/security/UserDetailsServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/KutsuController.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/KayttoOikeusRyhmaRepositoryCustom.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/criteria/MyontooikeusCriteria.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/KayttoOikeusRyhmaMyontoViiteRepositoryImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/KayttoOikeusRyhmaRepositoryImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/KayttajarooliProvider.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/PermissionCheckerService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttoOikeusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/PermissionCheckerServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/FunctionalUtils.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/KutsuHakuBuilder.java
- kayttooikeus-service/src/main/resources/db/migration/V20190530130411324__kayttooikeus_kutsu_create.sql
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/controller/KutsuControllerTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/controller/UserDetailsControllerTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/KayttoOikeusRyhmaRepositoryTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/populate/KayttoOikeusRyhmaPopulator.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/PermissionCheckerTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KayttoOikeusServiceTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KutsuServiceTest.java
> Virkailijan kutsumisen palvelukäyttäjänä

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/KayttajatiedotService.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttajatiedotServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KutsuServiceTest.java
> Korjaa kutsun käyttäjätunnuksen validoinnin

- kayttooikeus-service/src/main/resources/db/migration/V20190813171210000__koski_tilastokeskus_kayttooikeus.sql
Mahdollistaa kyselyn rajapintaan /koski/api/luovutuspalvelu/haku
> Lisää Kosken käyttöoikeus TILASTOKESKUS

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/KutsuRepository.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/KutsuRepositoryImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
- kayttooikeus-service/src/main/resources/db/migration/V20190910111511532__avoin_kutsu_sahkoposti.sql
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KutsuServiceTest.java
> Korjaa kutsulistauksen kun kutsujalla on passivoitu organisaatio

- kayttooikeus-service/src/main/resources/db/migration/V20191031132613000__koski_valvira_kayttooikeus.sql
mahdollistaa kyselyn rajapintaan /koski/api/luovutuspalvelu/valvira
> Lisää Kosken käyttöoikeus VALVIRA

- .travis.yml
- kayttooikeus-service/pom.xml
- kayttooikeus-service/src/main/resources/db/migration/V20191021113957131__yksityisten_rekisteroityminen_kayttooikeudet.sql
* lisää migraatioiden ajamisen CI:lle
* lisää palvelun & oikeudet yksityisten rekisteröitymiselle
> KJHH-1653 Varda yksityiset käyttöoikeus

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/KutsujaValidatorConfiguration.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/validators/KutsujaValidator.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/validators/KutsujaValidatorDisabledTest.java
- kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/validators/KutsujaValidatorEnabledTest.java
Hetu- ja yksilöintivaatimuksen voi poistaa Spring-profiililla testiympäristössä käytöstä
testaamisen helpottamiseksi.
> Kutsun hetu/yksilöintivalidointi disabloitavissa.

- kayttooikeus-service/src/main/resources/db/migration/V20210118091702000__valpas_kayttooikeudet.sql
Valpas-palvelu julkaistaan vaiheittain vuoden 2021 aikana. Oppilaitoksilla ja kunnilla on erilaiset vastuut ja oikeudet nähdä tietoja Valpas-järjestelmässä, joten lisätään erilliset käyttöoikeudet niille.
> [WIP] TOR-1160 Lisää uuden Valpas-palvelun käyttöoikeudet

- .travis.yml
- kayttooikeus-service/pom.xml
- Better support for local development
> KH-297: Test database migration against dockerized database

- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/KayttoOikeusRyhmaTapahtumaHistoriaRepositoryImpl.java
- kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/MyonnettyKayttoOikeusRyhmaTapahtumaRepositoryImpl.java
Prerequisite for: https://github.com/Opetushallitus/henkilo-ui/pull/178
> KJHH-1655: Add group description to response

- kayttooikeus-service/src/main/resources/db/migration/V20220117083011000__ytl_koski_ja_valpas_rajapinnat.sql
YTL:lle toteutetaan uudet API:t Koski-tietojen ja oppivelvollisuusrekisteritietojen hakua varten.
> TOR-1242 Lisää Kosken ja Valppaan YTL-APIen käyttöoikeudet

- kayttooikeus-service/src/main/resources/db/migration/V20230131140500000__koski_tpo_ja_muut_puuttuvat_roolit.sql
Lisää myös samalla puuttuva muun kuin säännellyn koulutuksen rooli
> Lisää Kosken taiteen perusopetuksen puuttuvat roolit
