kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/properties/CasProperties.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/properties/CommonProperties.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/properties/DatasourceProperties.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/properties/EmailInvitation.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/properties/HikariProperties.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/properties/ServiceUsersProperties.java

Previously preparing to new features in e.g. api tests caused problems when run against different branches. Would cause the same problem locally in development: a developer wouldn't be able to have configuration supporting different branches.

Allows ignoring of unknown properties in yml configurations.

---

kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/mapper/LocalDateConverter.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusServiceTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/PermissionCheckerTest.java

- Fix organisaatioviite to be checked from calling user organisations, not from the organisation to be granted.

KJHH-955_organisaatioviite

---

kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/HenkiloController.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/HenkiloHibernateRepository.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/criteria/HenkiloCriteria.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/HenkiloRepositoryImpl.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/util/HenkilohakuBuilder.java

- Kahteen eri hakuun koska postgres query planner ei osaa käyttää indeksejä nykyisessä haussa käyttäjänimille
- Muutentaan hakua paremmin käyttämään indeksejä

Kjhh 1117 henkilohaku optimointi

---

kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/KutsuService.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KutsuServiceTest.java

- Estää hetuttomia ja vtj-yksilöimättömiä virkailijoita luomasta kutsuja
- Ei kutsun henkilöä luodessa lisää uusia oikeuksia jos hetu on sama

Kjhh 1244 omien kutsujen käyttäminen

---

kayttooikeus-service/src/main/resources/db/migration/README.md
kayttooikeus-service/src/main/resources/db/migration/V20180502155850000__kayttooikeuksien_lisayksen_funktiot.sql
kayttooikeus-service/src/main/resources/db/migration/V20180502160232000__ulkoisten_rajapintojen_kayttooikeus.sql

Ulkoiset rajapinnat -palvelu sekä siihen liittyvä lukuoikeus puuttuu ainakin hahtuvalta ja tuotannosta authentication-tietokannasta.
ulkoiset-rajapinnat -sovellus edellyttää  APP_ULKOISETRAJAPINNAT_READ -käyttöoikeuden.

BUG-1724  ulkoiset rajapinnat -oikeudet

---

kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/CasController.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/IdentificationService.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/VahvaTunnistusService.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/IdentificationServiceImpl.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/VahvaTunnistusServiceImpl.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/VahvaTunnistusServiceTest.java

- Rajapintaan tuki pelkälle suomifi-kirjautumiselle ilman ennestään olemassa olevaa loginTokenia
- Vahvasti tunnistaa käyttäjän jos hetullinen virkailija löytyy mutta tunnistus puuttuu

KJHH-989: suomifi kirjautuminen

---

kayttooikeus-service/src/main/resources/db/migration/V20190108104646838__clear_sessions.sql
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/config/security/UserDetailsServiceImplTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/VahvaTunnistusServiceTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KayttajatiedotServiceTest.java
pom.xml

- SpringMvcTestit sisältävät nyt spring security filtterin jolloin testeihin tarvitaan lisää luokkia
- Tyhjentää vanhat sessiot

KJHH-1543: Update to spring boot 2.1.1

---

kayttooikeus-service/src/main/resources/db/migration/V20190128155053000__koski_arkaluontoisia_kayttooikeuksia.sql

- Lisää Kelalle kaksi käyttöoikeutta (suppeat ja laajat oikeudet)
- Nimeää vanhan kaikkiin oikeuttavan käyttöoikeuden uudelleen siten, että
nimestä käy käyttötarkoitus ilmi paremmin

Kosken arkaluontoisten tietojen käyttöoikeuksia

---

kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/KayttoOikeusRyhmaDto.java
kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/KayttoOikeusRyhmaModifyDto.java
kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/KutsuCreateDto.java
kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/MyonnettyKayttoOikeusDto.java
kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/UpdateHaettuKayttooikeusryhmaDto.java
kayttooikeus-domain/src/main/java/fi/vm/sade/kayttooikeus/model/KayttoOikeusRyhma.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/mapper/KayttoOikeusRyhmaConverter.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/mapper/KutsuCreateKayttoOikeusRyhmaConverter.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/AnomusController.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/KayttoOikeusRyhmaRepository.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/KayttoOikeusRyhmaRepositoryCustom.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/KayttoOikeusRyhmaTapahtumaHistoriaRepository.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/KayttoOikeusRyhmaRepositoryImpl.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/KayttoOikeusService.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusService.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/KutsuService.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/EmailServiceImpl.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttoOikeusServiceImpl.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
kayttooikeus-service/src/main/resources/db/migration/V20190125163725041__kayttooikeusryhma_allowed_usertype.sql
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/KayttoOikeusRyhmaRepositoryTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/populate/KayttoOikeusRyhmaPopulator.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/EmailServiceTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttoOikeusServiceUnitTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusServiceTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KayttoOikeusServiceTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KutsuServiceTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/util/CreateUtil.java

- Toiminto käyttöoikeusryhmän merkkaamiseksi vain palvelukäyttäjille myönnettäväksi
- Estetään vain palvelukäyttäjälle tarkoitettujen käyttöoikeusryhmien myöntäminen virkailijalle anomuksissa, kutsuissa ja suorassa käyttöoikeuksien myöntämisessä
- Tällaiseen käyttöoikeusryhmään anotun oikeuden voi kuitenkin hylätä anomukselta

KJHH-1519: kayttooikeusryhma rajoite

---

kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/KayttoOikeusRyhmaController.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/KutsuController.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/KayttoOikeusRyhmaRepositoryCustom.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/impl/KayttoOikeusRyhmaRepositoryImpl.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/KayttoOikeusService.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttoOikeusServiceImpl.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttooikeusAnomusServiceImpl.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/validators/HaettuKayttooikeusryhmaValidator.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/controller/KayttoOikeusRyhmaControllerTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/KayttoOikeusRyhmaRepositoryTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/KayttooikeusAnomusServiceTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KayttoOikeusServiceTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KutsuServiceTest.java

- Antaa rekisterinpitäjän aktivoida passivoitu käyttöoikeusryhmä
- Antaa rekisterinpitäjän hakea ja muokata passivoitu käyttöoikeusryhmä
- Antaa rekisterinpitäjän listata passivoidut käyttöoikeusryhmät
- Ei salli passivoitua käyttöoikeusryhmää kutsua tai anomusta luodessa ja suoraan käyttöoikeutta myönnettäessä
- Ohittaa kutsun kautta passivoituun käyttöoikeusryhmään myönnettävät oikeudet
- Sallii kuitenkin anomuksen hylkäämisen passivoituun käyttöoikeusryhmään

KJHH-1526: passiiviset koryhmat

---

kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/PermissionCheckerServiceImpl.java

Suoritusrekisteri is supposed to be able to take care of
it's own hakemus based permission checks now that
SEC-68 is deployed (on 11th of April 2019), so we can
remove them checks in from here.

SEC-68 : Remove old permission check fallback

---

kayttooikeus-service/src/main/resources/db/migration/V20190507165330000__koski_vain_esiopetus_kayttooikeus.sql

Rajaa organisaation Koski-lukuoikeuden vain esiopetuksen
opiskeluoikeuksiin.

Lisää Kosken käyttöoikeus LUKU_ESIOPETUS

---

kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/HenkiloController.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KayttajatiedotServiceImpl.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/controller/HenkiloControllerTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/it/KayttajatiedotServiceTest.java

Käyttäjätunnuksen luonti on sallittu vain palvelukäyttäjille,
muuten vain olemassa olevan käyttäjätunnuksen muokkaaminen on
sallittu.
Virkailijatunnukset tulee luoda aina kutsun kautta.
KJHH-1614

Korjaa käyttäjätunnuksen luonnin validoinnin

---

kayttooikeus-service/src/main/resources/db/migration/V20200430090919622__kayttooikeuden_poisto_funktion_korjaus.sql

Funktion voi nyt ajaa ilman virheitä olemattomalle käyttöoikeudelle.
Funktion omistajaksi vaihdettu 'oph'.

Käyttöoikeuden poisto -funktion korjaus.

---

kayttooikeus-service/src/main/resources/db/migration/V20201216115706000__koski_vapaan_sivistystyon_oikeudet.sql

Vapaan sivistystyön opintoja ei ole aiemmin ollut Koski-palvelussa tallennettuna, jatkossa tulee olemaan. Niitä järjestävien organisaatioiden käyttäjiä varten tarvitaan erillinen opiskeluoikeustyyppikohtainen käyttöoikeus.

TOR-1170 Lisää Koski VST käyttöoikeudet

---

kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/controller/CasController.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/VahvaTunnistusServiceImpl.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/controller/CasControllerUnitTest.java

* Shibboleth uses UTF-8 encoding for propagating HTTP headers
* Tomcat defaults to ISO-8859-1 for decoding HTTP headers
* First and last names are read from HTTP headers
* Names typically contain charaters (e.g. umlauts) which will break
due to the encoding mismatch
* -> Need to manually decode HTTP headers which may contain
"sensitive" charaters

KJHH-1934: Refactor: Move shibboleth header decoding to controller

---

kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/security/casoppija/SuomiFiAuthenticationProcessingFilter.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/config/security/casoppija/SuomiFiAuthenticationProcessingFilterTest.java

Joidenkin esimerkkien mukaan löytyy avaimella "firstName",
joidenkin "FirstName". Jälkimmäinen todennäköisemmin oikea,
joten korjattu käyttämään sitä; takaporttina mikäli ei löydy,
etsitään toisella.

Kludge etunimien hakemiseen attribuuteista.

---

kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/properties/KayttooikeusProperties.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/scheduling/IdentificationCleanupTask.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/scheduling/SchedulingClusterConfiguration.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/repositories/KayttajatiedotRepository.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/config/scheduling/IdentificationCleanupTaskTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/repositories/impl/KayttajatiedotRepositoryImplTest.java

* Identification is tied to user details but stored separately. this
may lead to situation where login is prevented when username is
being reused.
* This is simplified approach for solving given problem e.g. does not solve the actual problem but mitigates consequences
* PR created prior taking to actual testing

KJHH-2095: Add scheduled task for purging obsoleted identifications

---

kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/OrganisaatioServiceImpl.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/impl/OrganisaatioServiceImplTest.java

Data is used by henkilö UI to resolve organisation parent names, actual organisation name is obtained by other means -> leaves are not needed. Seems that this has has considerable effect on payload size (811kB -> 147kB)

Shrink payload size by omitting leafs from organisation names response

---

kayttooikeus-api/src/main/java/fi/vm/sade/kayttooikeus/dto/KutsuCreateDto.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/config/HttpClientConfiguration.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/EmailService.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/external/impl/ExternalPermissionClientImpl.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/EmailServiceImpl.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/KutsuServiceImpl.java
kayttooikeus-service/src/main/java/fi/vm/sade/kayttooikeus/service/impl/email/SahkopostiHenkiloDto.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/EmailServiceTest.java
kayttooikeus-service/src/test/java/fi/vm/sade/kayttooikeus/service/external/ExternalPermissionClientTest.java

Lisätty kutsuja kenttä kutsurajapintaan jolla voidaan välittää valinnaiset kutsujan tiedot suoraan sähköposti tempateen sen sijaan että sen pitäisi aina olla henkilö. Samallla tässä tuli puoli vahingossa korjaus tikettiin https://jira.eduuni.fi/browse/KJHH-2206 kun päivitin ophttpclientin yksinkertaisempaan toteutukseen.

Uusi tekstikenttä "kutsuja" kutsurajapintaan.
